### ISSUE TITLE
Migrate external postings to this website

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ScalaWilliam.com#55]
So that we follow [POSSE](https://indieweb.org/POSSE) and own our own stuff.

- [x] Unit testing is simple (dev.to, #77)
- [x] 2017 freelance development platforms (dev.to) (#85)
- [x] Certifications I'm considering, as an experienced software engineer (dev.to, #72)
- [x] What are advantages of Scala over Kotlin? (Quora, #86)
- [x] Why Scala didn't miss the Android opportunity (#65, Medium)
- [x] How I deal with greenfield technical debt (#70, Medium)
- [x] Java 8 Nashorn CLI use case: prepending ISO instant to CSV from UNIX timestamp (Medium, #87)
- [x] Limit degrees of freedom in development (#71, Medium)
- [x] Feature Switches, Inheritance and Agile with Scala & JMX on the JVM (#61, Medium)

**Comment by ScalaWilliam** [comment]
Anything beyond 4 paragraphs should be hosted on my own website primarily.

**Comment by Zegnat** [comment]
All of these now have PRs.

**Comment by ScalaWilliam** [comment]
Looks like it's solved. Thanks for your great help @Zegnat  and @brulzki !
